# preload = ~/.config/hypr/wallpapers/evangelion-shinji-unit-001-light.png
# wallpaper = ,~/.config/hypr/wallpapers/evangelion-shinji-unit-001-light.png

wallpaper {
	monitor = 
	path = ~/.config/hypr/wallpapers/evangelion-shinji-unit-001-light.png
}
